### ISSUE TITLE
ToDo plans

### ISSUE THREAD

**Issue by DiFFoZ** [EvolutionPlugins/EvolutionPlugins.Universal.Extras#1]
- [ ] Add HWID getter
- [ ] Add getter cancellation token of player death
- [ ] Add getter steam profile by id
- [ ] Add movement system (speed, gravity, jump)
- [ ] Add very basic clothing system
- [ ] Add README and samples usage
- [ ] Updater system OR notification of new version
- [ ] Raycast system
- [ ] User container (lifetime)
